---
- name: Deploy
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: pull image
      shell:
        cmd: docker pull {{docker_image}}
    - name: update image
      shell:
        cmd: docker service update --image {{docker_image}} traefik_nodejs
